"""add razorpay order id to payments

Revision ID: bda0cf591376
Revises: ab2956c0256f
Create Date: 2026-08-16 14:54:04.411356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda0cf591376'
down_revision: Union[str, Sequence[str], None] = 'ab2956c0256f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'payments', ['razorpay_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'razorpay_order_id')
    # ### end Alembic commands ###
